name: publish-ci
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@main
       - name: Login to GitHub Container Registry
         uses: docker/login-action@v1
         with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
       - name: Build the hello-docker Docker ci image
         run: |
           docker build . --tag ghcr.io/yominame/hello-docker-gcr-demo-ci:latest
           docker run ghcr.io/yominame/hello-docker-gcr-demo-ci:latest
           docker push ghcr.io/yominame/hello-docker-gcr-demo-ci:latest
