name: Actions Workflow 

on:
  push:
    tags: 
      - prod-*
      - uat-*
      - qa-*
        
jobs: 
  run-shell-command:
    runs-on: ubuntu-latest
    steps: 
      - name: echo a string
        run: echo "Hello World"
        timeout-minutes: 0
      - name: multiline script 
        run: |
           node -v 
           npm -v
      - name: python Command 
        run: |
          import platform 
          print
          (platform.processor())
        shell: python
